replicaCount: 1

image:
  repository: "pinkmelon/hrd-portal"
  tag: 112

service:
  type: NodePort
  port: 8081

revisionHistoryLimit: 3

# Add this for ConfigMap name
configMapName: auth-service-config
